#!/bin/bash
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`


[ $(echo -e "No\nYes" | dmenu -i -p "$1" -nb '#1E1E1E' -sf '#1E1E1E' -sb '#2266FF' -nf '#2266FF') == "Yes" ] && $2
