#!/bin/sh

# Get the full query. The 'echo | dmenu' idiom may be a bit of
# a hack, but it seems to work.
q="$(echo | dmenu)"
[ -z "$q" ] && exit 0

# Extract the engine code.
e="${q%% *}"

# Encode the search string (i.e. the rest of q). xxd was formerly used
# here, but xxd is part of vim packages on some systems, whereas od is
# ubiquitous. A search script that breaks if someone accidentally removes
# vim is stupid.
s=$(printf %s "${q#* }" | tr -d '\n' | od -t x1 -An |  tr ' ' '%')

# 'i' = imslp in startpage.com
# 'w' = wikipedia.org
# 'a' = wiki.archlinux.org
# 'd' = en.wiktionary.org
case $e in
    'i')
        xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://startpage.com/do/search?q=imslp+${s}"
        ;;
    'w')
        xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wikipedia.org/wiki/index.php/Special:Search?search=${s}&go=Go"
        ;;
    'a')
        xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://wiki.archlinux.org/index.php/Special:Search?search=${s}&go=Go"
        ;;
    'd')
        xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wiktionary.org/w/index.php?search=${s}&go=Go"
        ;;
    *)
        xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://startpage.com/do/search?q=${s}"
        ;;
esac
